[package]
name = "process-stream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tap          = "1.0.1"
futures      = "0.3.21"
tokio        = { version = "1.18.0", features = [ "rt-multi-thread", "macros", "process"] } 
tokio-stream = { version = "0.1.8", features = ["io-util"] }
async-stream = "0.3.3"
